version: '2.3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -uroot -p"${DB_ROOT_PASSWORD}"
      interval: 30s
      timeout: 5s
      retries: 15

  starter:
    build: .
    env_file:
      - .env
    environment:
      GUNICORN_CMD_ARGS: "--log-level info --reload --access-logfile /var/log/gunicorn.log"
    volumes:
      - ./starter:/app
      - ./docker-entrypoint-init.d/45-django-admin.sh:/docker-entrypoint-init.d/45-django-admin.sh
    ports:
      - "8020:80"
    healthcheck:
      test: curl -s http://localhost/healthcheck || exit 1
      interval: 30s
      timeout: 5s
      retries: 15
    depends_on:
      db:
        condition: service_healthy

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8021:80"
    environment:
      PMA_HOST: "db"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy
