"""
Django settings for starter project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from configurations import Configuration, values


class Common(Configuration):
    """This is the common site settings configuration."""

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent

    # Application definition
    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "health_check",
        "health_check.db",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

    ROOT_URLCONF = "starter.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "starter.wsgi.application"

    # Password validation
    # https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/3.2/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.2/howto/static-files/

    STATIC_URL = values.Value("/static", environ_name="DBMI_APP_STATIC_URL_PATH") + "/"
    STATIC_ROOT = values.Value("/var/static", environ_name="DBMI_APP_STATIC_ROOT")

    # Default primary key field type
    # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    # Set a test runner to hand test runs off to pytest
    # https://docs.djangoproject.com/en/3.2/ref/settings/#test-runner

    TEST_RUNNER = "tests.runner.PytestTestRunner"


class Production(Common):
    """This is the production site settings configuration."""

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = values.SecretValue(environ_prefix="", environ_required=True)

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False

    # Allowed Hosts
    # https://docs.djangoproject.com/en/3.2/ref/settings/#allowed-hosts
    ALLOWED_HOSTS = values.ListValue(environ_prefix="", environ_required=True)

    # Database
    # https://docs.djangoproject.com/en/3.2/ref/settings/#databases
    DATABASES = {
        "default": {
            "ENGINE": values.Value(environ_prefix="DB", environ_required=True),
            "NAME": values.Value(environ_prefix="DB", environ_required=True),
            "USER": values.Value(environ_prefix="DB", environ_required=True),
            "PASSWORD": values.Value(environ_prefix="DB", environ_required=True),
            "HOST": values.Value(environ_prefix="DB", environ_required=True),
            "PORT": values.Value(environ_prefix="DB", environ_required=True),
        }
    }


class Test(Common):
    """This is the settings configuration to use for testing."""

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = "thisisasecretkeythatisnotusedinanyactualenvironment"

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    # Allowed Hosts
    # https://docs.djangoproject.com/en/3.2/ref/settings/#allowed-hosts
    ALLOWED_HOSTS = ["*"]

    # Database
    # https://docs.djangoproject.com/en/3.2/ref/settings/#databases
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
