name: Requirements Update

on:
  schedule:
    - cron: '0 12 * * 3' # runs at 12:00 UTC on Wednesdays
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dev Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt

    - name: Check for pip-tools upgrades
      run: |
        pip-compile --upgrade requirements.in

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        branch: requirements-updates
        branch-suffix: timestamp
        delete-branch: true
        commit-message: "fix(requirements): Updated Python requirements"
        title: 'Python Requirements Updates'
        body: >
          This PR is auto-generated by Github Actions job [requirements-update].
        labels: dependencies, automated pr
