name: Requirements Update

on:
  schedule:
    - cron: '0 12 * * 1' # runs at 12:00 UTC on Mondays
  workflow_dispatch:

jobs:
  scan:
    uses: hms-dbmi/actions/.github/workflows/requirements-update.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python_version: "3.12"
      base_branch: "development"
      requirements_input: "requirements.in"
      requirements_output: "requirements.txt"
      dev_requirements: "dev-requirements.txt"
